version: '3'
services:
  app:
    build:
      context: ./docker/app
    image: isucon8-qualify-app:golang
    networks:
      - frontend
      - backend
    depends_on:
       - db
    ports:
      - "8080:8080"
    environment:
      DB_DATABASE: torb
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: isucon
      DB_PASS: isucon
  db:
    build:
      context: ./docker/db
    image: isucon8-qualify-db
    ports:
      - "3306"
    networks:
      - backend
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/logs:/var/log/mysql
    command: ["--character-set-server=utf8mb4"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  bench:
    build:
      context: ./docker/bench
    image: isucon7-qualifiy-bench
    depends_on:
      - app
    networks:
      - frontend
networks:
  frontend:
  backend: